In [16]:
import numpy as np       #imported numoy library
import pandas as pd      #imported pandas library
np.__version__           #version check 

'1.14.5'

In [4]:
#creating list of 10 numbers
L=list(range(10)) 
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
#Creating array of Zeros
Z=np.zeros(10, dtype='int')
print(Z)

[0 0 0 0 0 0 0 0 0 0]


In [6]:
#Creating 3 X 5 matrix of all ones
One=np.ones((3,5) ,dtype=float)
print(One)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
#create an array with a set sequence
SeqSet=np.arange(0,20,2)
print(SeqSet)

[ 0  2  4  6  8 10 12 14 16 18]


In [11]:
#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
T=np.random.normal(0,1,(3,3))
print(T)

[[ 0.38950155 -0.40223162 -0.59423972]
 [-1.17458994  0.46259092 -1.46833331]
 [ 1.97807234  0.08208736 -0.5419244 ]]


In [12]:
#Creating identity Matrix
I=np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
#Slice elements from start to 4th position
S=np.arange(10)
print(S[:4])

[0 1 2 3]


In [15]:
#Slice from 4th position to end
print(S[4:])

[4 5 6 7 8 9]


In [17]:
#create a data frame - dictionary is used here where keys get converted to column names and values to row values.
data = pd.DataFrame({'Country': ['Russia','Colombia','Chile','Equador','Nigeria'],
                    'Rank':[121,40,100,130,11]})
data

Country  Rank
0    Russia   121
1  Colombia    40
2     Chile   100
3   Equador   130
4   Nigeria    11

In [18]:
# quick analysis of any data set using:
data.describe()

Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

In [19]:
#To get the complete information about the data set, we are using info() function.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
Country    5 non-null object
Rank       5 non-null int64
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes


In [20]:
#Let's create another data frame to perform more operations.
data = pd.DataFrame({'group':['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [21]:
#sort the data frame by ounces - inplace = True will make changes to the data
data.sort_values(by=['ounces'],ascending=True,inplace=False)

group  ounces
1     a     3.0
6     c     3.0
0     a     4.0
7     c     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     b     8.0
2     a    12.0

In [22]:
#Sort by multiplr coulmns 
data.sort_values(by=['group','ounces'],ascending=[True,False],inplace=False)

group  ounces
2     a    12.0
0     a     4.0
1     a     3.0
5     b     8.0
4     b     7.5
3     b     6.0
8     c     6.0
7     c     5.0
6     c     3.0

In [23]:
#remove duplicates
data.drop_duplicates()

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0